spring:
  application:
    name: small-business-management

  datasource:
    url: jdbc:mysql://localhost:3306/shop_management
    username: root
    password: your_password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  jackson:
    time-zone: Asia/Kolkata